### ISSUE TITLE
Missing permissions on pull

### ISSUE THREAD

**Issue by antho1404** [graphcool/graphql-cli#15]
I know this is still a work in progress but this might help maybe.

On my project I'm able to fetch my permissions but some of them seems not to have an ID and I have the following yaml

```yaml
- operation: Contract.create
  authenticated: true
  query: ./query/.graphql
- operation: Contract.update
  authenticated: true
  query: ./query/.graphql
```

Because of that the same file `./query/.graphql` is re-written for many permissions so I cannot have them all

If you want to reproduce the project id is `cj4npwuofoqsc0118oels7lio` and my CLI version is `1.3.8`

Sorry if this is already a known bug or even already fixed
